/**
 * Calibrated Speaker Reconciliation Configuration
 *
 * GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: scripts/calibrate-reconciliation.ts
 * Generated on: 2026-01-27
 *
 * Calibration corpus: 10 synthetic conversations with ground truth
 * Grid search space: 2880 combinations
 * Recall constraint: >= 0.80 (prevents excessive over-fragmentation)
 *
 * Best F1 score: 0.9231
 * Precision: 1.0000
 * Recall: 0.8571
 */

export const CalibratedReconciliationConfig = {
  /** Edge threshold for clustering (baseline before adaptive adjustment) */
  edgeThreshold: 0.45,

  /** Cohesion threshold for cluster merging (quality-adjusted baseline) */
  cohesionThreshold: 0.38,

  /** Temporal half-life in seconds for temporal proximity weighting */
  temporalHalfLife: 120,

  /** Quality floor: exclude speakers below this quality score */
  qualityFloor: 0.15,

  // Calibration metadata
  calibrationF1: 0.9231,
  calibrationPrecision: 1.0000,
  calibrationRecall: 0.8571,
  calibrationDate: '2026-01-27',
  minRecallConstraint: 0.80,

  // True/False positives/negatives on calibration corpus
  calibrationMetrics: {
    truePositives: 30,
    falsePositives: 0,
    falseNegatives: 5
  }
};
