/**
 * Calibrated Speaker Reconciliation Configuration
 *
 * GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: scripts/calibrate-reconciliation.ts
 * Generated on: 2026-01-24
 *
 * Calibration corpus: 10 synthetic conversations with ground truth
 * Grid search space: 1512 combinations
 *
 * Best F1 score: 0.8846
 * Precision: 1.0000
 * Recall: 0.7931
 */

export const CalibratedReconciliationConfig = {
  /** Edge threshold for clustering (baseline before adaptive adjustment) */
  edgeThreshold: 0.48,

  /** Cohesion threshold for cluster merging (quality-adjusted baseline) */
  cohesionThreshold: 0.45,

  /** Temporal half-life in seconds for temporal proximity weighting */
  temporalHalfLife: 120,

  /** Quality floor: exclude speakers below this quality score */
  qualityFloor: 0.15,

  // Calibration metadata
  calibrationF1: 0.8846,
  calibrationPrecision: 1.0000,
  calibrationRecall: 0.7931,
  calibrationDate: '2026-01-24',

  // True/False positives/negatives on calibration corpus
  calibrationMetrics: {
    truePositives: 23,
    falsePositives: 0,
    falseNegatives: 6
  }
};
